cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import (
	ItemListView,
	ItemDetailView,
	ItemUpdateView,
	ItemCreateView,
	)
urlpatterns = [
    url(r'^$', ItemListView.as_view(),name='list'),
    url(r'^create/$',ItemCreateView.as_view(),name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(),name='detail'),
]

cfehome/src/testproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from profiles.views import ProfileFollowToggle,RegisterView,activate_user_view
from menus.views import HomeView
from quickstartREST.views import UserViewSet,GroupViewSet
from rest_framework import routers
from restaurants.views import (RestaurantListView,RestaurantDetailView,RestaurantCreateView)
from django.views.generic import TemplateView

# for RESTFUL applications
# http://www.django-rest-framework.org/api-guide/routers/
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    # Standard views via CFE tutorials
    url(r'^$', HomeView.as_view(),name="home"),
    url(r'^u/', include('profiles.urls',namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'),name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'),name='contact'),
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')),
    url(r'^items/', include('menus.urls',namespace='menus')),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(),name="follow"),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # Activation view with slug
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view,name='activate'),
    # testing views
    url(r'^plaid/', include('plaidtest.urls',namespace='plaidtest')),
    url(r'^background-zoom/$', TemplateView.as_view(template_name='background-zoom.html'),name='background-zoom'),
    url(r'^parallax/$', TemplateView.as_view(template_name='parallax.html'),name='parallax'),
    url(r'^carousel/$', TemplateView.as_view(template_name='carousel.html'),name='carousel'),
    # RESTFUL API reroutes
    url(r'^', include(router.urls)),
]   #,email=settings.EMAIL_HOST_USER to access settings.py

cfehome/src/templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>

cfehome/src/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
	{{form.errors.non_field_errors}}
{% endif %}	
<form method='POST'> {% csrf_token %}
		{{form.as_p}}
<button type="submit">Save</button>
</form>

cfehome/src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script>
function w3_open() {
  document.getElementById("main-collapsable").style.marginLeft = "15%";
  document.getElementById("mySidebar").style.width = "15%";
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("openNav").style.display = 'none';}
function w3_close() {
  document.getElementById("main-collapsable").style.marginLeft = "0%";
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("openNav").style.display = "inline-block";
}
var lFollowX = 0,
    lFollowY = 0,
    x = 0,
    y = 0,
    friction = 1 / 30;

function moveBackground() {
  x += (lFollowX - x) * friction;
  y += (lFollowY - y) * friction;
 
  translate = 'translate(' + x + 'px, ' + y + 'px) scale(1.03)';

  $('.background-main').css({
    '-webit-transform': translate,
    '-moz-transform': translate,
    'transform': translate
  });

  window.requestAnimationFrame(moveBackground);
}

$(window).on('mousemove click', function(e) {

  var lMouseX = Math.max(-100, Math.min(100, $(window).width() / 2 - e.clientX));
  var lMouseY = Math.max(-100, Math.min(100, $(window).height() / 2 - e.clientY));
  lFollowX = (20 * lMouseX) / 100; // 100 : 12 = lMouxeX : lFollow
  lFollowY = (10 * lMouseY) / 100;

});
$(document).ready(function(){
  $(".slick-carousel").slick({
        autoplay: true,
        arrows:false,
      });
});
function toggleWorkAround(){
  if ($("#collapseExample").css("display")=='none'){
    document.getElementById("collapseExample").style.display = "inline-block"
  }else if($("#collapseExample").css("display")=='inline-block'){
    console.log('inline detected')
    document.getElementById("collapseExample").style.display = "none";
  }
}
</script>

cfehome/src/templates/snippets/nav.html
<a href='{% url "home" %}'class="w3-bar-item w3-button">Home </a>
<a href='{% url "about" %}'class="w3-bar-item w3-button">About </a>
<a href='{% url "contact" %}'class="w3-bar-item w3-button">Contact</a>
<a href='{% url "background-zoom" %}'class="w3-bar-item w3-button">Background Zoom</a>
<a href='{% url "parallax" %}'class="w3-bar-item w3-button">Parallax</a>
<a href='{% url "carousel" %}'class="w3-bar-item w3-button">Carousel</a>
{% if request.user.is_authenticated %}
<a href='{% url "restaurants:list" %}'class="w3-bar-item w3-button">Restaurants </a>
<a href='{% url "menus:list" %}'class="w3-bar-item w3-button">Menu Items </a>
<a href='{% url "plaidtest:auth" %}'class="w3-bar-item w3-button">Plaid </a>
<!-- no reverse lookup in native routers, requires custom router to implement -->
<a href='/users/' class="w3-bar-item w3-button"'> REST</a>
<a href='{% url "register" %}'class="w3-bar-item w3-button"> Logout </a>
{%endif%}
{%if not request.user.is_authenticated %}
<a href='{%url "register" %}' class="w3-bar-item w3-button"> Register </a>
<a href='{%url "login" %}' class="w3-bar-item w3-button"> Login </a>
{%endif%}

cfehome/src/templates/snippets/search_bar.html
<form class='form' method='GET' action='/u/'>
	<input type="text" name="q" placeholder='Search..' value ='{{request.GET.q}}'>
	<button
	class='btn btn-default' type='submit'>Search</button>
</form>

cfehome/src/templates/snippets/sidebar.html
{%comment %}
need viewport for scaling when moving
{%endcomment%}
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none" id="mySidebar">
  <button class="w3-bar-item w3-button w3-large" onclick="w3_close()">Close &times;</button>
  {% include 'snippets/nav.html'%}
</div>
<div id="main-collapsable">
	<div class="w3-blue">
		{%comment %}
	  &#9776; is alt code for triple bar
	  {%endcomment%}
	  <button id="openNav" class="w3-button w3-teal w3-xlarge" onclick="w3_open()">&#9776;</button>
	  {%comment %}
	  \ work as escape characters just the same as other languages
	  {%endcomment%}
	    Welcome {{request.user}}, it is the: {%now "jS \o\f F Y P" %}
	</div>
</div>