cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import (
	ItemListView,
	ItemDetailView,
	ItemUpdateView,
	ItemCreateView,
	)
urlpatterns = [
    url(r'^$', ItemListView.as_view(),name='list'),
    url(r'^create/$',ItemCreateView.as_view(),name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(),name='detail'),
]

cfehome/src/testproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from profiles.views import ProfileFollowToggle,RegisterView,activate_user_view
from menus.views import HomeView
from quickstartREST.views import UserViewSet,GroupViewSet
from rest_framework import routers
from restaurants.views import (RestaurantListView,RestaurantDetailView,RestaurantCreateView)
from django.views.generic import TemplateView

# for RESTFUL applications
# http://www.django-rest-framework.org/api-guide/routers/
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    # Standard views via CFE tutorials
    url(r'^$', HomeView.as_view(),name="home"),
    url(r'^u/', include('profiles.urls',namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'),name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'),name='contact'),
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')),
    url(r'^items/', include('menus.urls',namespace='menus')),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(),name="follow"),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # Activation view with slug
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view,name='activate'),
    # testing views
    url(r'^plaid/', include('plaidtest.urls',namespace='plaidtest')),
    url(r'^background-zoom/$', TemplateView.as_view(template_name='background-zoom.html'),name='background-zoom'),
    url(r'^parallax/$', TemplateView.as_view(template_name='parallax.html'),name='parallax'),
    url(r'^carousel/$', TemplateView.as_view(template_name='carousel.html'),name='carousel'),
    # RESTFUL API reroutes
    url(r'^', include(router.urls)),
]   #,email=settings.EMAIL_HOST_USER to access settings.py

cfehome/src/menus/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from restaurants.models import RestaurantLocation

class Item(models.Model):
	user 			= models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant		= models.ForeignKey(RestaurantLocation)
	name 			= models.CharField(max_length=120)
	content 		= models.TextField(help_text='seperate each item by comma')
	excludes		= models.TextField(blank=True,null=True, help_text='seperate each item by comma')
	public 			= models.BooleanField(default=True)
	timestamp 		= models.DateTimeField(auto_now_add=True)
	updated 		= models.DateTimeField(auto_now=True)
	# image_url

	class Meta:
		ordering = ['-updated','-timestamp'] #reverse item.object.all to give recent updated item first
	def get_content(self):
		return self.content.split(",")
	def get_excludes(self):
		return self.excludes.split(",")
	def get_absolute_url(self):#get_absolute_url
		return reverse('menus:detail',kwargs={'pk':self.pk})
	def __str__(self):
		return self.name

cfehome/src/menus/forms.py
from django import forms
from restaurants.models import RestaurantLocation
from .models import Item
class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = [
			'restaurant',
			'name',
			'content',
			'excludes',
			'public'
		]
	def __init__(self, user=None,*args, **kwargs):
		super(ItemForm,self).__init__(*args,**kwargs)
		self.fields['restaurant'].queryset=RestaurantLocation.objects.filter(owner=user)#.exclude(item__isnull=False) empty setsa

cfehome/src/menus/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,View

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Item
from .forms import ItemForm

class HomeView(View):
	def get(self,request,*args,**kwargs):
		if not request.user.is_authenticated():
			return render(request,"home.html",{})
		user=request.user
		is_following_uid = [x.user.id for x in user.is_following.all()]
		qs=Item.objects.filter(user__id__in=is_following_uid,public=True).order_by("-updated")[:3]
		return render(request,"menus/home-feed.html",{'object_list':qs})

class ItemListView(LoginRequiredMixin,ListView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemDetailView(LoginRequiredMixin,DetailView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin,CreateView):
	template_name='form.html'
	form_class = ItemForm
	def form_valid(self,form):
		instance = form.save(commit=False)
		instance.user= self.request.user
		return super(ItemCreateView,self).form_valid(form)
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)
	def get_form_kwargs(self):
		kwargs=super(ItemCreateView,self).get_form_kwargs()
		kwargs['user'] = self.request.user
		kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
		return kwargs
	def get_context_data(self,*args,**kwargs):
		context = super(ItemCreateView,self).get_context_data(*args, **kwargs)
		context['title']='Create Item'
		return context

class ItemUpdateView(LoginRequiredMixin,UpdateView):
	template_name='menus/detail-update.html'
	form_class = ItemForm	
	def get_form_kwargs(self):
		kwargs=super(ItemUpdateView,self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)
	def get_context_data(self,*args,**kwargs):
		context = super(ItemUpdateView,self).get_context_data(*args, **kwargs)
		context['title']='Update Item'
		return context

cfehome/src/menus/templates/menus/detail-update.html
{%extends "base.html"%}
{%block head_title %}{{form.instance.name}} Menus Items || {{block.super}}{% endblock head_title %}
{%block content %}
{{ form|crispy }}
<h1>{{form.instance.name}}</h1>
<p>Location: {{form.instance.restaurant.name}}</p>
<ul>
	{%if form.instance.content%}
	Contents
	<ul>
		{% for item in form.instance.get_content %}
		<li>
			{{item}}
		</li>
		{%endfor%}
	</ul>
	{%endif%}
	{%if form.instance.excludes%}
	Excludes
	<ul>
		{% for item in form.instance.get_excludes %}
		<li>
			{{item}}
		</li>
		{%endfor%}
	</ul>
	{%endif%}
	</li>
</ul>
<h3> Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}
{%endblock%}

cfehome/src/menus/templates/menus/home-feed.html
{%extends "base.html"%}
{%block head_title %}Home Feed || {{block.super}}{% endblock head_title %}
{%block content %}


<h1> User Following Feed</h1>
{%for obj in object_list%}
<div class='row'>
	<div class= 'col-sm-11 text-center'>
		<div class='card bg-dark text-white border-info mb-3'>
			<div class="card-header">
				<h7>{{obj.name}}</h7> 
			</div>
			<h7><a href='{% url "profiles:detail" username=obj.user.username %}'>{{obj.user.username}}</a></h7>
			<p> {{obj.restaurant.title}} | {{obj.restaurant.category}}</p>
			<p><b>{{obj.name}}: </b> with
				{%for ing in obj.get_content %}
				<a href ='{{request.path}}?q={{ ing}}'>{{ing}}</a>
				{%endfor%}
			</p>
		</div>
		{%endfor%}	
	</div>
</div>
{%endblock%}

cfehome/src/menus/templates/menus/item_detail.html
{%extends "base.html"%}
{%block head_title %}menus items || {{block.super}}{% endblock head_title %}
{%block content %}
<h1>{{object.name}}</h1>
<p>Location: {{object.restaurant.name}}</p>
<ul>
	{%if object.content%}
	Contents
	<ul>
		{% for item in object.get_content %}
		<li>
			{{item}}
		</li>
		{%endfor%}
	</ul>
	{%endif%}
	{%if object.excludes%}
	Excludes
	<ul>
		{% for item in object.get_excludes %}
		<li>
			{{item}}
		</li>
		{%endfor%}
	</ul>
	{%endif%}
	</li>
</ul>
{%endblock%}

cfehome/src/menus/templates/menus/item_list.html
{%extends "base.html"%}
{%block head_title %}menus items || {{block.super}}{% endblock head_title %}
{%block content %}
<h1> Menus List<small><a href={% url "menus:create" %}>  Add</a></small></h1><hr>
<ul>
	{%for obj in object_list %}
	<li>
		<a href='{{obj.get_absolute_url}}'>{{obj.name}}</a></br>
		{%if obj.content%}
		Contents
		<ul>
			{% for item in obj.get_content %}
			<li>
				{{item}}
			</li>
			{%endfor%}
		</ul>
		{%endif%}
		{%if obj.excludes%}
		Excludes
		<ul>
			{% for item in obj.get_excludes %}
			<li>
				{{item}}
			</li>
			{%endfor%}
		</ul>
		{%endif%}
	</li>
	{%empty%}
		<a href={% url "menus:create" %}>  Add</a>
	{% endfor %}
</ul>
{%endblock%}